import { mkdir, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const logoDirectory = path.join(root, "public", "stock-logos");
const outputPath = path.join(root, "src", "generated", "stockLogoFiles.ts");

async function main() {
  const entries = await readdir(logoDirectory, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".png"))
    .map((entry) => entry.name.slice(0, -4).toLowerCase())
    .sort((left, right) => left.localeCompare(right, "en"));
  const source = [
    "// Generated by scripts/build_stock_logo_manifest.mjs. Do not edit manually.",
    `export const stockLogoFiles = new Set<string>(${JSON.stringify(files)});`,
    "",
  ].join("\n");
  await mkdir(path.dirname(outputPath), { recursive: true });
  const temporaryPath = `${outputPath}.${process.pid}.tmp`;
  try {
    await writeFile(temporaryPath, source, "utf8");
    await rename(temporaryPath, outputPath);
  } finally {
    await rm(temporaryPath, { force: true });
  }
  console.log(`Generated ${path.relative(root, outputPath)} with ${files.length} local logo files.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
